### PR TITLE
add nearspark (thumbnails server)

### PR DESCRIPTION
**Pull request by XuHaoJun**

### CODE REVIEW

**Comment by albirrkarim** [comment]
What is that?

**Comment by XuHaoJun** [comment]
The Spoke Search Media API (https://github.com/mozilla/Spoke/blob/master/src/api/Api.js#L430) resizes images to 200x200, e.g. Sketchfab media source. This resizing service is provided by Nearspark.

```typescript
    const thumbnailedEntries = json.entries.map(entry => {
      if (entry.images && entry.images.preview && entry.images.preview.url) {
        if (entry.images.preview.type === "mp4") {
          entry.images.preview.url = proxiedUrlFor(entry.images.preview.url);
        } else {
          entry.images.preview.url = scaledThumbnailUrlFor(entry.images.preview.url, 200, 200);
        }
      }
      return entry;
    });
```

**Comment by albirrkarim** [comment]
image

So your sketchfab section in spoke is work ?

**Comment by XuHaoJun** [comment]
Screenshot_2023-02-23_20-54-39

To obtain a Sketchfab API key, go to (https://sketchfab.com/settings/password). Once you have obtained the API key, you can set it in the `config/dev.exs` file of Reticulum as shown in the following:
```elixir
config :ret, Ret.MediaResolver,
  giphy_api_key: nil,
  deviantart_client_id: nil,
  deviantart_client_secret: nil,
  imgur_mashape_api_key: nil,
  imgur_client_id: nil,
  youtube_api_key: nil,
  sketchfab_api_key: "YOUR_API_KEY_HERE",
  ytdl_host: nil,
  photomnemonic_endpoint: "https://uvnsm9nzhe.execute-api.us-west-1.amazonaws.com/public"
```

and same in `config/dev.exs` append `https://nearspark-dev.reticulum.io` to `asset_hosts` if you won't self-host nearspark.
```elixir
asset_hosts =
  "https://localhost:4000 https://localhost:8080 " <>
    "https://#{host}:4000 https://#{host}:8080 https://#{host}:3000 https://#{host}:8989 https://#{host}:9090 https://#{cors_proxy_host}:4000 " <>
    "https://assets-prod.reticulum.io https://asset-bundles-dev.reticulum.io https://asset-bundles-prod.reticulum.io https://hubs.local:5000 " <>
    "https://nearspark-dev.reticulum.io"
```

Sketchfab tab should work.

I can submit a new pull request that includes a description of the Sketchfab settings in reticulum tomorrow.

**Comment by albirrkarim** [comment]
Ok, i got it, I think it's not the main part of hubs. The purpose of the main tutorial on `readme.md` its for quick install the Hubs. so keep it short and don't make the user overload with other detailed information.

and the `PROBLEM_SOVLED.md` it is for the other detailed thing like a solution for the feature that doesn't work, etc.

So please write it on the  `PROBLEM_SOVLED.md` 

https://github.com/albirrkarim/mozilla-hubs-installation-detailed/blob/main/PROBLEM_SOLVED.md

Thank you for contributing.

**Pull request merged**
